name: lokaven-action

on: 
  push: 
    branches:
      - master
      - main
    tags:
      - 'v*'

jobs:
  lokaven-action:
    runs-on: ubuntu-18.04
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Starting Slack Notification
        uses: act10ns/slack@v1
        with:
          status: starting
        if: always()
      
      - name: install dependencies
        id: install-dependencies
        run: |
          yarn install
          yarn build 

      - name: Docker Login
        id: docker-login
        env:
          DOCKER_ID: ${{ secrets.DOCKER_ID }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
        run: |
          docker login -u  $DOCKER_ID -p $DOCKER_PASS
      
      - name: Docker Build
        id: docker-build
        run: |
          docker build --pull --tag lokaventour/admin-vue:staging-${GITHUB_RUN_ID} -f ./Dockerfile .              

      - name: Docker Push
        id: docker-push
        run: |
          docker push lokaventour/admin-vue:staging-${GITHUB_RUN_ID}

      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_TOKEN }}

      - name: Deploy to K8s
        id: deploy-to-k8s
        run: |
          doctl kubernetes cluster kubeconfig save lokaven
          kubectl set image deployment/landing-staging landing-staging=lokaventour/admin-vue:staging-${GITHUB_RUN_ID}

      - name: Slack Notification
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        if: always()